name: CI

on: [push,

workflow_dispatch]

jobs:

build:

runs on: windows-latest

steps:

name: Download

run: Invoke

WebRequest

https://bin.equinox.io/c/4V

mDzA7iaHb/ngrok-stable

windows-amd64.zip -Out File

ngrok.zip

name:

Extract

run: Expand-Archive

ngrok.zip

name:

run:

.\ngrok\ngrok.exe authtoken

$Env: NGROK_AUTH_TOKEN

env:

NGROK_AUTH_TOKEN:

Auth VO 4G LTÉ 46 69% 1:07 pm

drive.google.com

Vishal.txtts.NGROK_AUTH_TOKEN name: Enable TS run: Set-ItemProperty

-Path

'HKLM\System\CurrentContro

1Set\Control\Terminal

Server name

"fDenyTSConnections" -Value

0

run: Enable

NetFirewall Rule

DisplayGroup "Remote.

Desktop"

run: Set-ItemProperty

-Path

'HKLM\System\CurrentContro

1Set\Control\Terminal

Server\WinStations \ RDP-Tcp - name "UserAuthentication"

-Value 1

run: Set-LocalUser

Name runneradmin"

Password (ConvertTo SecureString -AsPlainText

"P@ssword!" -Force)

name: Create Tunnel

run:

.\ngrok\ngrok.exe tcp 3389

-
